max_n_agents: 3

# Agent Actions
grab_box: true
grab_out_of_vision: true
grab_selective: false
grab_exclusive: false

lock_box: true
lock_ramp: true
lock_type: "all_lock_team_specific"
lock_out_of_vision: True

# Scenario
n_substeps: 15
horizon: 80
scenario: "quadrant"
n_rooms: 4
random_room_number: true
prob_outside_walls: 0.5
prep_fraction: 0.4
rew_type: "joint_zero_sum"
restrict_rect:
  - 0.1
  - 0.1
  - 5.9
  - 5.9

# hiders_together_radius: 0.5
# seekers_together_radius: 0.5

# Objects
n_boxes: 1
n_elongated_boxes: 0
box_only_z_rot: true
boxid_obs: false

n_ramps: 1

# Food
n_food: 0
max_food_health: 40
food_radius: 0.5
food_box_centered: true
food_together_radius: 0.25
food_respawn_time: 5
food_rew_type: "joint_mean"

# Observations
n_lidar_per_agent: 30
visualize_lidar: false
prep_obs: true