algorithm_name: rmappo
env_name: StarCraft2
map_name: 3m
user_name: garrett4wade
experiment_name: 256cores
benchmark: false
cuda: true
cuda_deterministic: true
seed: 1
use_eval: false
use_wandb: false
use_render: false
no_summary: true

num_env_steps: 10000000
train_for_env_steps: 10000000000
train_for_seconds: 600
model_dir: null

# system parameters
model_weights_addr: tcp://10.0.2.2:8889
seg_addrs:
  - tcp://10.0.2.2:12346
  - tcp://10.0.2.2:12347
  - tcp://10.0.2.2:12348
  - tcp://10.0.2.2:12349
  - tcp://10.0.2.2:12350
  - tcp://10.0.2.2:12352
  - tcp://10.0.2.2:12353
  - tcp://10.0.2.2:12354
  - tcp://10.0.2.2:12355
  - tcp://10.0.2.2:12356
num_actors: 128
envs_per_actor: 4
num_policy_workers: 4
qsize: 32
num_splits: 2
num_trainers: 1
num_transmitters: 1
min_num_requests: -1
data_chunk_length: 10
slots_per_update: 1
episode_length: 400

# fixed system parameters
stats_avg: 100
set_workers_cpu_affinity: true
force_envs_single_thread: true
default_niceness: 0
eval_episodes: 32
eval_interval: 25
log_interval: 20
n_eval_rollout_threads: 4
n_training_threads: 16
reset_timeout_seconds: 60
actor_worker_gpus: 0

# algorithm parameters
hidden_size: 64
layer_N: 1
rec_n: 1
sample_reuse: 5
num_mini_batch: 1
lr: 0.0005
max_grad_norm: 10.0
entropy_coef: 0.01
gamma: 0.99
gae_lambda: 0.95
gain: 0.01
value_coef: 1.0
weight_decay: 0
opti_eps: 1.0e-05
clip_param: 0.2
huber_delta: 10.0

# render parameters
ifi: 0.1
render_episodes: 5
save_gifs: false
save_interval: 1

# tricks
share_policy: true
use_fct_masks: true
use_feature_normalization: true
use_gae: true
use_huber_loss: true
use_linear_lr_decay: false
use_max_grad_norm: true
use_orthogonal: true
use_popart: true
use_proper_time_limits: false
use_ReLU: true
use_active_masks: true
use_advantage_normalization: true
use_centralized_V: true
use_clipped_value_loss: true

# some fixed tricks
add_agent_id: false
add_center_xy: true
add_distance_state: false
add_enemy_action_state: false
add_local_obs: false
add_move_state: false
add_visible_state: false
add_xy_state: false
use_stacked_frames: false
stacked_frames: 1
use_state_agent: true
use_mustalive: true
use_obs_instead_of_state: false
